"""
core/question_service.py
========================
Question service for SQL generation.

This service handles CLI question processing, SQL generation,
and validation.
"""

from typing import Optional, Tuple, Dict, Any
import re

from ai.simple_query_generator import generate_simple_sql
from ai.sql_generator import generate_sql, generate_sql_with_retry
from utils.question_normalizer import normalize_question, is_too_ambiguous
from utils.sql_validator import validate_sql, validate_sql_structure, add_limit_if_missing
from conversation.followup_detector import detect_follow_up
from conversation.question_rewriter import rewrite_follow_up_question
from conversation.action_detector import detect_conversation_action
from conversation.conversation_memory import ConversationMemory
from utils.logger import get_logger

logger = get_logger()

_UNSAFE_NL_RE = re.compile(
    r"\b(delete|drop|update|insert|alter|truncate|create|remove|destroy)\b",
    re.IGNORECASE,
)


class QuestionService:  
    """Service for question processing and SQL generation."""
    
    def __init__(self):
        self.conversation_memory = ConversationMemory() 
    
    def process_question(
        self,
        question: str,
        knowledge_base: Dict[str, Any],
        business_glossary: Optional[Dict[str, Any]] = None,
        ai_backend: str = "local",
    ) -> Tuple[bool, str, Optional[str], Optional[str]]:
        """
        Process a natural language question and generate SQL.
        
        Args:
            question: User's natural language question
            knowledge_base: Knowledge base for SQL generation
            business_glossary: Business glossary for question rewriting
            ai_backend: AI backend to use for SQL generation
        
        Returns:
            (success, message, sql, error)
        """
        if _UNSAFE_NL_RE.search(question):
            return False, "Unsafe request blocked. Only SELECT questions are allowed.", None, None

        # Check for ambiguity
        if is_too_ambiguous(question):
            return False, "Question is too ambiguous. Please be more specific.", None, None
        
        # Normalize question
        normalized_question, was_normalized = normalize_question(question)
        if was_normalized:
            logger.info(f"Question normalized: '{question}' -> '{normalized_question}'")
            question = normalized_question
        
        # Check for conversation actions
        action = detect_conversation_action(question)
        if action:
            return False, f"Action detected: {action}", None, None
        
        # Detect follow-up
        is_follow_up, followup_reason = detect_follow_up(question, self.conversation_memory)
        rewritten_question = question
        
        if is_follow_up:
            logger.info(f"Follow-up detected: {followup_reason}")
            try:
                rewritten_question = rewrite_follow_up_question(
                    question,
                    self.conversation_memory,
                    knowledge_base,
                    business_glossary,
                    ai_backend,
                )
                logger.info(f"Rewritten question: {rewritten_question}")
            except Exception as e:
                logger.warning(f"Follow-up rewrite failed: {e}, using original question")
                rewritten_question = question
        
        # Try simple SQL generator first
        simple_sql = generate_simple_sql(rewritten_question, knowledge_base)
        
        if simple_sql:
            logger.info("SQL generated using simple query generator")
            is_valid, reason = validate_sql(simple_sql)
            if not is_valid:
                logger.error(f"Generated SQL failed safety check: {reason}")
                return False, f"Generated SQL failed safety check: {reason}", None, None
            
            struct_ok, struct_reason = validate_sql_structure(simple_sql, knowledge_base)
            if not struct_ok:
                logger.error(f"Generated SQL failed structure check: {struct_reason}")
                return False, f"Generated SQL failed structure check: {struct_reason}", None, None
            
            # Add turn to conversation memory
            self.conversation_memory.add_turn(
                user_question=question,
                is_follow_up=is_follow_up,
                rewritten_question=rewritten_question,
                generated_sql=simple_sql,
            )
            
            return True, "SQL generated successfully (simple generator)", simple_sql, None
        
        # Use AI SQL generation for complex questions
        logger.info("Using AI for SQL generation")
        try:
            raw_sql = generate_sql(rewritten_question, knowledge_base, backend=ai_backend)
            logger.info(f"SQL generated by AI: {raw_sql[:100]}...")
        except Exception as e:
            logger.error(f"SQL generation failed: {e}")
            return False, f"SQL generation failed: {e}", None, None
        
        # Add LIMIT if missing
        candidate_sql = add_limit_if_missing(raw_sql.strip())
        
        # Validate safety
        safety_ok, safety_reason = validate_sql(candidate_sql)
        # Validate structure
        struct_ok, struct_reason = validate_sql_structure(candidate_sql, knowledge_base)
        
        if safety_ok and struct_ok:
            logger.info("First SQL attempt passed validation")
            # Add turn to conversation memory
            self.conversation_memory.add_turn(
                user_question=question,
                is_follow_up=is_follow_up,
                rewritten_question=rewritten_question,
                generated_sql=candidate_sql,
            )
            return True, "SQL generated successfully (AI)", candidate_sql, None
        
        # Retry with correction prompt
        fail_reason = safety_reason if not safety_ok else struct_reason
        logger.warning(f"First SQL attempt failed: {fail_reason}. Retrying...")
        
        try:
            retry_raw = generate_sql_with_retry(
                user_question=rewritten_question,
                knowledge_base=knowledge_base,
                backend=ai_backend,
                first_attempt_sql=candidate_sql,
                validation_reason=fail_reason,
            )
        except Exception as e:
            logger.error(f"SQL generation failed after retry: {e}")
            return False, f"SQL generation failed after retry: {e}", None, None
        
        retry_sql = add_limit_if_missing(retry_raw.strip())
        retry_safety_ok, retry_safety_reason = validate_sql(retry_sql)
        retry_struct_ok, retry_struct_reason = validate_sql_structure(retry_sql, knowledge_base)
        
        if retry_safety_ok and retry_struct_ok:
            logger.info("Retry SQL attempt passed validation")
            # Add turn to conversation memory
            self.conversation_memory.add_turn(
                user_question=question,
                is_follow_up=is_follow_up,
                rewritten_question=rewritten_question,
                generated_sql=retry_sql,
            )
            return True, "SQL generated successfully (AI, corrected)", retry_sql, None
        
        # Both attempts failed
        final_reason = retry_safety_reason if not retry_safety_ok else retry_struct_reason
        logger.error(f"SQL generation failed after retry: {final_reason}")
        return False, f"SQL generation failed: {final_reason}", None, None
    
    def validate_sql(self, sql: str, knowledge_base: Optional[Dict[str, Any]] = None) -> Tuple[bool, str]:
        """
        Validate SQL for safety and structure.
        
        Args:
            sql: SQL to validate
            knowledge_base: Knowledge base for structure validation
        
        Returns:
            (is_valid, reason)
        """
        # Validate safety
        is_valid, reason = validate_sql(sql)
        if not is_valid:
            return False, reason
        
        # Validate structure if knowledge base is available
        if knowledge_base:
            struct_ok, struct_reason = validate_sql_structure(sql, knowledge_base)
            if not struct_ok:
                return False, struct_reason
        
        return True, "SQL is valid"
    
    def detect_action(self, question: str) -> Optional[str]:
        """
        Detect if the question is a conversation action.
        
        Args:
            question: User's question
        
        Returns:
            Action string or None
        """
        return detect_conversation_action(question)
    
    def reset_conversation(self) -> None:
        """Reset conversation memory."""
        self.conversation_memory = ConversationMemory()
    
    def get_conversation_memory(self) -> ConversationMemory:
        """Get conversation memory."""
        return self.conversation_memory
